require('dotenv').config();

const CONFIG = {};

CONFIG.BASE_URL = process.env.REACT_APP_BASE_URL || 'http://localhost:3000';
CONFIG.API_URL = process.env.REACT_APP_API_URL;
CONFIG.GOOGLE_API_KEY = process.env.REACT_APP_GOOGLE_API_KEY || '';
CONFIG.APP_PUSHER_APP_KEY = process.env.REACT_APP_PUSHER_APP_KEY || '';
CONFIG.APP_PUSHER_ORDER_CHANNEL =
  process.env.REACT_APP_PUSHER_ORDER_CHANNEL || 'order-channel';
CONFIG.APP_PUSHER_PAYOUT_CHANNEL =
  process.env.REACT_APP_PUSHER_PAYOUT_CHANNEL || 'payout-channel';
CONFIG.ELASTIC_SEARCH_LINK = process.env.REACT_APP_ELASTIC_SEARCH_LINK || '';
CONFIG.ELASTIC_USERNAME = process.env.REACT_APP_ELASTIC_USERNAME || '';
CONFIG.ELASTIC_PASSWORD = process.env.REACT_APP_ELASTIC_PASSWORD || '';
CONFIG.CLOUDIMG_BASE_URL = process.env.REACT_APP_CLOUDIMG_BASE_URL || '';
CONFIG.CAPSULE_WEBSITE_KEY = process.env.REACT_APP_CAPSULE_WEBSITE_KEY || '';
CONFIG.DIGITAL_OCEAN_SPACES = process.env.REACT_APP_DIGITAL_OCEAN_SPACES || '';
CONFIG.STRIPE_CLIENT_ID = process.env.REACT_APP_STRIPE_CLIENT_ID || '';
CONFIG.STRIPE_PUBLIC_KEY = process.env.REACT_APP_STRIPE_PUBLIC_KEY || '';

module.exports = CONFIG;
